export const CASTLE_BIOME = 'Castle'
export const FIELD_BIOME = 'Field'
export const FOREST_BIOME = 'Forest'
export const LAKE_BIOME = 'Lake'
export const GRASSLAND_BIOME = 'Grassland'
export const SWAMP_BIOME = 'Swamp'
export const MINE_BIOME = 'Mine'
