export const CASTLE_BIOME = 'CASTLE'
export const FIELD_BIOME = 'FIELD'
export const FOREST_BIOME = 'FOREST'
export const LAKE_BIOME = 'LAKE'
export const GRASSLAND_BIOME = 'GRASSLAND'
export const SWAMP_BIOME = 'SWAMP'
export const MINE_BIOME = 'MINE'
